version: '3.8'
services:
  apache:
    image: php:8.1-apache
    container_name: apache_server
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bogota_vibes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # Add this line to include mime types
      - ./nginx/mime.types:/etc/nginx/mime.types
    ports:
      - "80:80"  # Changed to standard HTTP port for easier access
    depends_on:
      - apache

volumes:
  db_data: